### ISSUE TITLE
Non-zero exit with RuntimeException after successfully uploading the report

### ISSUE THREAD

**Issue by vivsrivastav** [mwz/sbt-sonar#39]
I am using sbt-sonar version  `1.7`. The report generation works fine & publishes to Sonarqube. After the report is published sbt-sonar returns with an exit code of 1 which causes the build to fail.

Command executed `sbt +clean +package +coverage +test +coverageReport sonarScan`
Here is the exception log
```
[info] INFO: ------------- Run sensors on project
[info] INFO: Sensor Zero Coverage Sensor
[info] INFO: Sensor Zero Coverage Sensor (done) | time=1ms
[info] INFO: 1 file had no CPD blocks
[info] INFO: Calculating CPD for 6 files
[info] INFO: CPD calculation finished
[info] INFO: Analysis report generated in 82ms, dir size=196 KB
[info] INFO: Analysis report compressed in 45ms, zip size=50 KB
[info] INFO: Analysis report uploaded in 127ms
[info] INFO: ANALYSIS SUCCESSFUL, you can browse https://sonar.mycompany.com/dashboard?id=key%3Ascv
[info] INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
[info] INFO: More about the report processing at https://sonar.mycompany.com/api/ce/task?id=AWuudVQx0SSBxUIOMGwC
[info] INFO: Analysis total time: 11.438 s
[info] INFO: ------------------------------------------------------------------------
[info] INFO: EXECUTION SUCCESS
[info] INFO: ------------------------------------------------------------------------
[info] INFO: Total time: 14.328s
[info] INFO: Final Memory: 58M/820M
[info] INFO: ------------------------------------------------------------------------
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at scala.sys.process.BasicIO$Streamed$.next$1(BasicIO.scala:49)
[error]         at scala.sys.process.BasicIO$Streamed$.$anonfun$apply$1(BasicIO.scala:50)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error]         at scala.collection.immutable.Stream.foreach(Stream.scala:530)
[error]         at sbtsonar.SonarPlugin$.$anonfun$projectSettings$3(SonarPlugin.scala:77)
[error]         at sbtsonar.SonarPlugin$.$anonfun$projectSettings$3$adapted(SonarPlugin.scala:52)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (moduleA / sonarScan) Nonzero exit code: 1
``` 

**Build.sbt**
```
name := "lib-xyz"

inThisBuild(Seq(
  organization := "my-org",
  javacOptions ++= Seq("-source", "1.8", "-target", "1.8"),
  scalacOptions ++= Seq(
    "-feature",
    "-deprecation",
    "-unchecked",
    "-language:postfixOps",
    "-language:higherKinds",
	  "-language:implicitConversions",
    "-Ypartial-unification"
  )
))

lazy val root = project.in(file("."))
  .settings(
    moduleName := "root"
  )
  .aggregate(moduleA)
  .settings(sonarSettings)

lazy val moduleA = project
  .settings(
    libraryDependencies ++= Seq(
        cats.core, cats.effect,
        http4sAsyncClient, http4sDsl, fs2core, fs2io,
        jsoup, scalaTestInTests, journal
    ),
    addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.9"),
    publishMavenStyle := true,
    publishArtifact := true,
  )

lazy val sonarSettings = Seq(
  sonarProperties ++= Map(
    "sonar.projectName" -> "myproject",
    "sonar.projectKey" -> "key:myproject",
    "sonar.modules" -> "moduleA",
    "module1.sonar.projectName" -> "moduleA",
    "sonar.sources" -> "src/main/scala",
    "sonar.junit.reportPaths" -> "target/test-reports",
    "sonar.scala.coverage.reportPaths" -> "target/scala-2.12/scoverage-report/scoverage.xml", 
    "sonar.java.binaries" -> "target/scala-2.12/classes",
    "sonar.login" -> "69174626AF5144E9A43DE60CFCADF646",
    "sonar.host.url" -> "https://sonar.mycompany.com",
  )
)
```

**Comment by mwz** [comment]
Can you try adding the following setting in your root project so that the `sonarScan` task gets run only once?
`.settings(aggregate in sonarScan := false)`

Check out the example [here](https://github.com/mwz/sbt-sonar/blob/master/src/sbt-test/sbt-sonar/multi-module/build.sbt) for a reference.

**Comment by mwz** [comment]
Also FYI, you can skip setting some of the settings in your example as they are set automatically by the plugin (see the README file), e.g.: 
- `sonar.projectName` - defaults to your project name defined in the `name` sbt setting key;
- `sonar.projectKey` - defaults to your project name transformed into lowercase and dash-separated value;
- `sonar.sources` - defaults to the value of `scalaSource in Compile` which conventionally is `src/main/scala`;
